wmww/gtk-layer-shell

- meson.build
With a dependency gtk-layer-shell can be used as a submodule very easily:
```
gtk_layer_shell = dependency('gtk-layer-shell-0', fallback: ['gtk-layer-shell', 'gtk_layer_shell_dep'])
```
> meson.build: add custom dependency for easy usage as subproject

- src/layer-surface.c
Cleans up the logic and fixes #11 (with net negative LoC no less!). Hopefully doesn't break anything. I've tested both the built-in examples and mate-panel on both Sway and Mir, and all seems to work. @ammen99 can you confirm that this fixes your issue?
> Improve layer surface sizing

- src/meson.build
Some distributions (at least Fedora) prohibit packaging unversioned .so libraries.
This is a minimal change to generate versioned libgtk-layer-shell.so.0*. Feel free to discard this if you have more sophisticated library versioning scheme in mind.
> Build versioned library

- demo/gtk-layer-demo.c
- demo/gtk-layer-demo.h
- demo/margin-control.c
- demo/mscl-toggles.c
- include/gtk-layer-shell.h
- src/layer-surface.c
This hopefully fixes #24 without breaking #11 again. It also adds a new toggle to gtk-layer-demo that can be used to test. Before merging, I hope to get approval from both @ammen99 and @hraisins confirming it works for their use cases (test with your actual projects, not just gtk-layer-demo). How to use (as explained in the public header):
> If you wish to force your layer surface window to be a different size than it is by default:
```c
gtk_widget_set_size_request (GTK_WIDGET (layer_gtk_window), width, height);
gtk_window_resize (layer_gtk_window, 1, 1); // force the window to resize to the new request
```
> If width or height is -1, the default is used for that axis. If the window is anchored to opposite edges of the output (see `gtk_layer_set_anchor ()`), the size request is ignored. …
> Allow users to set size along a non-anchored axis

- src/layer-surface.c
This fixes cases in which the size of the output becomes smaller in a stretched direction. Easy to test with `gtk-layer-demo` by running it in a Sway instance nested under Wayland/X and shrinking the Sway window. I'd like to get approval from both @ammen99 and @hraisins that this doesn't break anything before merging (I'm pretty confident it fixes the bug it intends to, just not that it doesn't break any other use cases).
> Fix resizing on new configure

- src/gtk-wayland.c
- src/layer-surface.c
- src/protocol/wlr-layer-shell-unstable-v1.xml
Just a minor change to avoid remapping when the compositor implements zwlr_layer_surface_v1 version 2+.
Tested on sway with gtk-layer-demo.
> Use layer_surface->set_layer instead of remapping when available

- src/custom-shell-surface.c
- src/gtk-priv-access.c
- src/gtk-priv-access.h
- src/xdg-popup-surface.c
Fixes #9. About damn time. Verified to work with the oldest GTK version we claim to support (3.22.0).
__By opening this pull request, I agree for my modifications to be licensed under the same license as the files they are made to (which may be a permissive license)__
> Fix grabbing popups

- meson.build
- src/gtk-wayland.c
- src/protocol/meson.build
This change matters when linking as a static library or meson subproject
to the project that is already building xdg-shell protocol of a
different version. In this case linker would prefer symbols from the
main project.
If both the main project and the subproject are using the same xdg-shell
protocol definition from the system wayland-protocols, the chance of
things going wrong is slightly lesser
> Use system xdg-shell protocol when available

- demo/gtk-layer-demo.c
- demo/gtk-layer-demo.h
- demo/mscl-toggles.c
Initial size was not being set when `--fixed-size` was specified. Exclusive zone was being set, but incorrectly. This fixes both.
Fixes #64
> Demo: fix initial exclusive zone and size

- src/layer-surface.c
- test/meson.build
- test/test-clients/test-auto-exclusive-zone-weird-bool-values.c
The code in this file assumes that all true gbooleans are equal. That's
not correct and it's acceptable, albeit discouraged, to assign any int
value to gboolean. Of course in this case any strict equality checks in
this file could fail.
Fixes auto exclusive zone when passing values other than TRUE or FALSE
to `gtk_layer_set_anchor`.
***
For reference, this is how waybar code looked before I finally decided to figure out why auto exclusive zone doesn't work.
```c++
gtk_layer_set_anchor(
gtk_window, GTK_LAYER_SHELL_EDGE_LEFT, anchor_ & ZWLR_LAYER_SURFACE_V1_ANCHOR_LEFT);
gtk_layer_set_anchor(
gtk_window, GTK_LAYER_SHELL_EDGE_RIGHT, anchor_ & ZWLR_LAYER_SURFACE_V1_ANCHOR_RIGHT);
gtk_layer_set_anchor(
gtk_window, GTK_LAYER_SHELL_EDGE_TOP, anchor_ & ZWLR_LAYER_SURFACE_V1_ANCHOR_TOP); …
```
> Normalize boolean values for anchors.

- CHANGELOG.md
- include/gtk-layer-shell.h
Add `Since: ...` annotations. Fixes #82.
> Add Since: annotations for missing functions

- test/check-licenses.py
Only scan a list of directories at the top level, instead of everything. This keeps the test from breaking every time someone introduces some new build dir or packaging data or whatever.
> License check: only scan some toplevel directories

- test/integration-tests/meson.build
- test/integration-tests/test-get-monitor.c
- test/integration-tests/test-set-monitor.c
- test/mock-server/overrides.c
This works locally on Ubuntu 20.04 with GTK v3.22.0 and GTK v3.24.20. It fails in CI for unknown reasons.
> Add monitor tests

- .gitignore
- test/README.md
- test/integration-test-common/integration-test-common.c
- test/integration-test-common/integration-test-common.h
- test/run-integration-test.py
Now when integration tests are run manually, user gets fun little continue button. Also clean up and type check the integration test script.
> Allow running integration tests interactivly

- src/custom-shell-surface.c
- src/gtk-priv-access.c
- src/gtk-priv-access.h
- test/integration-tests/meson.build
- test/integration-tests/test-create-subsurface.c
- test/mock-server/overrides.c
This fixes #38 with no known unwanted side-effects. `mapped` isn't supposed to be set for custom surfaces, but I dug through all the code that uses it without spotting anything that might cause a problem. This also adds a test for #38.
> Set layer surfaces to mapped

- meson_options.txt
- src/meson.build
Add an `introspection` option to the Meson build system which allows toggling generation of GObject-Introspection data. This can be useful for systems where G-I is not needed or not used.
> meson: Allow disabling gobject-introspection at build time

- include/gtk-layer-shell.h
Thank you for writing gtk-layer-shell!
I am updating and cleaning the Rust wrapper, which I automatically created using gir. I now added documentation but when I generate it, I get two warnings described in [issue 2](https://github.com/pentamassiv/gtk-layer-shell-gir/issues/2) of the repo.
I suggest to use % instead of # in the docs to show that it is a reference to a variant of an enum and not it's own type. This gets rid of the warning and at least the Rust docs don't seem to change from it. If I read [this comment](https://github.com/gtk-rs/gir/pull/1085#discussion_r603837736) correctly, the warning and the proposed changes make sense.
> Fix documentation to refer to variants

- test/run-integration-test.py
I noticed in #130 that unix color codes were erroneously being added to logs. The colored output doesn't even make it look that much better, so simplify things by dropping it.
> run-integration-test.py: don't produce color output

- doc/meson.build
This was introduced in https://github.com/wmww/gtk-layer-shell/pull/28
Pointed out by @Artturin in https://github.com/NixOS/nixpkgs/pull/211502#discussion_r1096323072
> Remove redundant dependency check for gtk-doc

- src/api.c
By opening this pull request, I agree for my modifications to be licensed under whatever licenses are indicated at the start of the files I modified
Reverts wmww/gtk-layer-shell#142 oops, code to do this check is already in layer-surface.c. It defaults to `none` instead of `exclusive`, which is probably a better choice.
> Revert "Show warning if on-demand keyboard interactivity is not supported"

- README.md
If the commands from the README.md are followed, the following deprecation warning is displayed when running meson:
```
WARNING: Running the setup command as `meson [options]` instead of `meson setup [options]` is ambiguous and deprecated.
```
This small change gets rid of it.
> Fix deprecation warning when running meson

- src/custom-shell-surface.c
- src/gtk-priv-access.c
- src/gtk-priv-access.h
- src/gtk-wayland.c
- src/gtk-wayland.h
- src/xdg-popup-surface.c
- src/xdg-toplevel-surface.c
Fixes #163. Replaces a messy (and broken) hack for getting window geometry. We have gtk-priv now, use it. 
> Use gtk-priv to get window geometry

- include/gtk-layer-shell.h
I noticed that the automatically generated comments of the Rust bindings for the keyboard modes are not at the correct place. The only difference I noticed was the missing @ symbols. I hope that is the reason why they don't get generated correctly but I am not sure.
> Fix comments of Keyboard Mode

- CHANGELOG.md
- compatibility.md
- gtk-priv/h/gdk_wayland_pointer_data_priv.h
- gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
- gtk-priv/h/gdk_wayland_seat_priv.h
- gtk-priv/h/gdk_wayland_tablet_data_priv.h
- gtk-priv/h/gdk_wayland_touch_data_priv.h
- gtk-priv/h/gdk_window_impl_class_priv.h
- gtk-priv/h/gdk_window_impl_priv.h
- gtk-priv/h/gdk_window_impl_wayland_class_priv.h
- gtk-priv/h/gdk_window_impl_wayland_priv.h
- gtk-priv/h/gdk_window_priv.h
- meson.build
> Release v0.8.2

- src/gtk-wayland.c
Fixes #173 
This seems to be necessary on KWin, otherwise regular xdg-toplevels would be detected as "unresponsible". Note: I assume that GTK already does this, but since we connect to xdg_wm_base separately, this seems required here as well (I don't know if KWin picks arbitrarily one xdg_wm_base object to send pings to or sends it to all of them though).
> gtk-wayland: handle xdg_wm_base::ping

- test/integration-tests/test-set-monitor.c
- test/run-integration-test.py
libwayland change their debug output format, which broke out tests. This should keep us compatible with both the old and the new.
Fixes #182 
> Make tests compatible with new libwayland format

- include/gtk-layer-shell.h
- src/api.c
- src/custom-shell-surface.c
- src/custom-shell-surface.h
- src/gtk-priv-access.c
- src/gtk-priv-access.h
Works for waybar and the test applications. Not 100% sure that it's safe though.
Fixes #185 
> Commit surface directly instead of relying on gtk_window_invalidate_rect

- src/custom-shell-surface.c
- src/layer-surface.c
Possibly fixes #135. Works on my tests in nested Sway, but ideally someone who was seeing the original issue would try it out. Sister PR to https://github.com/wmww/gtk4-layer-shell/pull/82.
> Remap surfaces when outputs change

- src/xdg-popup-surface.c
- test/mock-server/mock-server.h
- test/mock-server/overrides.c
This PR fixes a protocol error when creating XDG popups on wlroots-git.
Since commit [5dc73937](https://gitlab.freedesktop.org/wlroots/wlroots/-/commit/5dc73937ff96e17a7b4e136a80dfec087604878d) wlroots checks that the effective geometry of all xdg surfaces is nonempty when set. Since effective geometry is always clamped to the size of the attached surface, we can no longer set the window geometry while a nil buffer is attached to the surface.
Remove the call to `xdg_surface_set_window_geometry()` in `xdg_popup_surface_map()`, leaving only the call in
`xdg_popup_surface_on_size_allocate()`.
Fixes #200.
I'm not 100% sure the `xdg_surface_set_window_geometry()` call in `xdg_popup_surface_on_size_allocate()` is always triggered, but it appears to work in my personal testing. I'm open to …
> xdg-popup-surface: avoid setting window_geometry with no buffer attached
