wmww/gtk-layer-shell

- meson.build
Fixes #17, as suggested by @tristan957 [here](https://github.com/wmww/gtk-layer-shell/issues/4#issuecomment-524340814)
> Remove pedantic warnings

- meson.build
> Use gnu11 standard

- doc/gtk-layer-shell-docs.sgml
- doc/gtk-layer-shell.types
- doc/meson.build
- doc/xml/gtkdocentities.ent.in
- doc/xml/meson.build
- include/gtk-layer-shell.h
- meson.build
- meson_options.txt
Needs at least some more general verbiage and review. Could also use a build option. Build with:
```
ninja -C build gtk-layer-shell-doc
```
> First stab at gtk-doc for wmww/gtk-layer-shell#26

- .github/workflows/build.yml
Add basic CI script that at least makes sure it builds
> Add building in CI with GH actions

- .github/workflows/build.yml
- src/check_license.py
__By opening this pull request, I agree for my modifications to be licensed under the same license as the files they are made to (which may be a permissive license)__
> Improvements to license checker script

- .github/pull_request_template.md
- .github/workflows/check_pr.yml
> License agreement

- .github/workflows/build.yml
- .github/workflows/check_file_licenses.yml
- .github/workflows/check_pr.yml
Make the PR checks a little clearer
> Improve workflows

- src/custom-shell-surface.c
- src/xdg-popup-surface.c
- src/xdg-toplevel-surface.c
Fixes #51 and #47
@psnszsn does this solve the problem?
> Fix popover crash

- LICENSE_GPL.txt
- README.md
Clarify that we use LGPL v3 or any later version, and add a copy of the GPL as that is required. Thanks @jtojnar for raising these issues. Can you please review before I merge?
> License fixes

- gtk-priv/h/gdk_wayland_pointer_data_priv.h
- gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
- gtk-priv/h/gdk_wayland_seat_priv.h
- gtk-priv/h/gdk_wayland_tablet_data_priv.h
- gtk-priv/h/gdk_wayland_touch_data_priv.h
- gtk-priv/h/gdk_window_impl_class_priv.h
- gtk-priv/h/gdk_window_impl_priv.h
- gtk-priv/h/gdk_window_impl_wayland_class_priv.h
- gtk-priv/h/gdk_window_impl_wayland_priv.h
- gtk-priv/h/gdk_window_priv.h
> Support GTK v3.24.22

- include/gtk-layer-shell.h
- src/gtk-layer-shell.c
- src/layer-surface.c
- src/layer-surface.h
> Allow accessing the underlying layer shell surface

- CHANGELOG.md
- meson.build
> v0.3.0 release

- meson.build
- test/meson.build
- test/run-integration-test.py
- test/test-client-common/test-client-common.c
- test/test-client-common/test-client-common.h
- test/test-clients/basic-test.c
- test/test-clients/test-adapts-to-screen-size.c
- test/test-clients/test-anchors.c
- test/test-clients/test-auto-exclusive-zone-no-margin.c
- test/test-clients/test-auto-exclusive-zone-with-margin.c
- test/test-clients/test-expect-fail.c
- test/test-clients/test-set-layer.c
- test/test-clients/test-set-size-request.c
> Test additions and refactors

- .github/workflows/build_and_test.yml
- demo/gtk-layer-demo.c
- demo/version-info.c
- include/gtk-layer-shell.h
- meson.build
- src/gtk-layer-shell.c
- src/meson.build
- test/README.md
- test/meson.build
- test/unit-tests/test-get-version.c
Expose the library version in the API and show it in the demo
> Show gtk layer shell version

- CHANGELOG.md
- compatibility.md
- meson.build
- release_process.md
> 0.4.0 release

- CHANGELOG.md
- test/check-licenses.py
- test/license-ignore.txt
> Don't require git for license check

- test/check-licenses.py
> License check: always ignore build dirs

- src/custom-shell-surface.c
- test/meson.build
- test/mock-server/mock-server.c
- test/mock-server/mock-server.h
- test/mock-server/overrides.c
- test/run-integration-test.py
- test/test-clients/test-close-layer-surface.c
- test/test-clients/test-window-with-initially-attached-buffer.c
> Test surface with initial buffer

- CHANGELOG.md
- include/gtk-layer-shell.h
- src/api.c
- test/meson.build
- test/test-clients/test-is-layer-window.c
- test/test-clients/test-is-supported-true.c
> Add functions for check if supported and if attached to a window

- CHANGELOG.md
- compatibility.md
- meson.build
> Release v0.5.0

- test/check-licenses.py
- test/mock-server/overrides.c
- test/run-integration-test.py
Fixes #91, as well as improving the quality of the integration test runner in general. I'd like to get confirmation that this actually works before merging. After I merge this, I plan to make a v0.5.1 release.
> Fix integration tests timeout bug

- CHANGELOG.md
- compatibility.md
- meson.build
- test/check-licenses.py
- test/mock-server/overrides.c
- test/run-integration-test.py
> Release 0.5.1

- .github/workflows/build_and_test.yml
- README.md
- doc/gtk-layer-shell.types
- doc/meson.build
- examples/meson.build
- examples/vala-standalone/README.md
- examples/vala-standalone/main.vala
- examples/vala-standalone/meson.build
- src/meson.build
After some discussions in #5, I thought I ought to add a Vala example and add it to CI.
> Add Vala example

- README.md
- examples/simple-example.py
> Add python example

- README.md
Add badge to readme with a list of distro packages
> Add distro packages badge

- CHANGELOG.md
- compatibility.md
- gtk-priv/h/gdk_wayland_pointer_data_priv.h
- gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
- gtk-priv/h/gdk_wayland_seat_priv.h
- gtk-priv/h/gdk_wayland_tablet_data_priv.h
- gtk-priv/h/gdk_wayland_touch_data_priv.h
- gtk-priv/h/gdk_window_impl_class_priv.h
- gtk-priv/h/gdk_window_impl_priv.h
- gtk-priv/h/gdk_window_impl_wayland_class_priv.h
- gtk-priv/h/gdk_window_impl_wayland_priv.h
- gtk-priv/h/gdk_window_priv.h
- meson.build
- release_process.md
> Release 0.7

- include/gtk-layer-shell.h
> Bugfix header

- README.md
in meson_options.txt vapi is set to true
> README.md: fixed advised boolean value for `vapi`

- src/gtk-wayland.c
> Free child list

- compatibility.md
- gtk-priv/h/common.h
> Do not show GTK version warning by default

- CHANGELOG.md
- compatibility.md
- gtk-priv/h/gdk_wayland_pointer_data_priv.h
- gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
- gtk-priv/h/gdk_wayland_seat_priv.h
- gtk-priv/h/gdk_wayland_tablet_data_priv.h
- gtk-priv/h/gdk_wayland_touch_data_priv.h
- gtk-priv/h/gdk_window_impl_class_priv.h
- gtk-priv/h/gdk_window_impl_priv.h
- gtk-priv/h/gdk_window_impl_wayland_class_priv.h
- gtk-priv/h/gdk_window_impl_wayland_priv.h
- gtk-priv/h/gdk_window_priv.h
- meson.build
> Release v0.8

- src/api.c
> Show warning if on-demand keyboard interactivity is not supported

- meson.build
> Mark wayland-scanner as a build-time dependency

- .github/workflows/build_and_test.yml
> Switch CI from Ubuntu 18.04 to Ubuntu 22.04

- README.md
> Update README to note Plasma support

- CHANGELOG.md
- compatibility.md
- gtk-priv/h/common.h
- gtk-priv/h/gdk_wayland_pointer_data_priv.h
- gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
- gtk-priv/h/gdk_wayland_seat_priv.h
- gtk-priv/h/gdk_wayland_tablet_data_priv.h
- gtk-priv/h/gdk_wayland_touch_data_priv.h
- gtk-priv/h/gdk_window_impl_class_priv.h
- gtk-priv/h/gdk_window_impl_priv.h
- gtk-priv/h/gdk_window_impl_wayland_class_priv.h
- gtk-priv/h/gdk_window_impl_wayland_priv.h
- gtk-priv/h/gdk_window_priv.h
- meson.build
> Release v0.8.1

- src/xdg-popup-surface.c
Hard problem, easy fix
Fixes #141, fixes #160
> Fix popup dead zone

- gtk-priv/h/gdk_wayland_pointer_data_priv.h
- gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
- gtk-priv/h/gdk_wayland_seat_priv.h
- gtk-priv/h/gdk_wayland_tablet_data_priv.h
- gtk-priv/h/gdk_wayland_touch_data_priv.h
- gtk-priv/h/gdk_window_impl_class_priv.h
- gtk-priv/h/gdk_window_impl_priv.h
- gtk-priv/h/gdk_window_impl_wayland_class_priv.h
- gtk-priv/h/gdk_window_impl_wayland_priv.h
- gtk-priv/h/gdk_window_priv.h
- gtk-priv/scripts/version.py
> gtk-priv: fix bug and update

- README.md
- examples/demo/menu-bar.c
- src/custom-shell-surface.c
- src/custom-shell-surface.h
- src/gtk-wayland.c
- src/layer-surface.c
- src/xdg-popup-surface.c
- src/xdg-toplevel-surface.c
- test/integration-tests/meson.build
- test/integration-tests/test-menu-popup.c
- test/integration-tests/test-nested-popup-unmap-order.c
- test/integration-tests/test-nested-popup.c
- test/mock-server/overrides.c
> Always unmap popups before their parents

- CHANGELOG.md
- compatibility.md
- meson.build
> Release v0.9.0

- test/mock-server/overrides.c
This is ported from gtk4-layer-shell, see https://github.com/wmww/gtk4-layer-shell/pull/48 and it's linked issue for details.
I haven't observed any problems from not sending .release in *this* version yet, but have the fix then not.
> Mock server: send buffer release

- .github/workflows/deploy_docs.yml
Same as https://github.com/wmww/gtk4-layer-shell/pull/75
> Bump GH actions version related to docs deployment

- CHANGELOG.md
- compatibility.md
- gtk-priv/h/gdk_wayland_pointer_data_priv.h
- gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
- gtk-priv/h/gdk_wayland_seat_priv.h
- gtk-priv/h/gdk_wayland_tablet_data_priv.h
- gtk-priv/h/gdk_wayland_touch_data_priv.h
- gtk-priv/h/gdk_window_impl_class_priv.h
- gtk-priv/h/gdk_window_impl_priv.h
- gtk-priv/h/gdk_window_impl_wayland_class_priv.h
- gtk-priv/h/gdk_window_impl_wayland_priv.h
- gtk-priv/h/gdk_window_priv.h
- meson.build
> Release v0.9.1

- CHANGELOG.md
- gtk-priv/h/gdk_wayland_pointer_data_priv.h
- gtk-priv/h/gdk_wayland_pointer_frame_data_priv.h
- gtk-priv/h/gdk_wayland_seat_priv.h
- gtk-priv/h/gdk_wayland_tablet_data_priv.h
- gtk-priv/h/gdk_wayland_touch_data_priv.h
- gtk-priv/h/gdk_window_impl_class_priv.h
- gtk-priv/h/gdk_window_impl_priv.h
- gtk-priv/h/gdk_window_impl_wayland_class_priv.h
- gtk-priv/h/gdk_window_impl_wayland_priv.h
- gtk-priv/h/gdk_window_priv.h
- meson.build
> Release v0.9.2
